#how many files reference this project (me <- them)
match $p isa project has project_name "<githubRepo>";
$fi isa file; (has_defines: $p, is_defines: $fi) isa defines;
$fu isa function; (has_defines: $fi, is_defines: $fu) isa defines;
$fi_ref isa file; (has_ref: $fi_ref, is_ref: $fu) isa ref;
$p_ref isa project; (has_defines: $p_ref, is_defines: $fi_ref) isa defines;
$p_ref != $p;
aggregate count;