#which methods are copied in this project
match $p isa project has project_name "<githubRepo>";
$fi isa file; (has_defines_file: $p, is_defines_file: $fi) isa defines_file;
$fi has file_location $file_location;
$fu isa function-instance; (has_defines_function: $fi, is_defines_function: $fu) isa defines_function;
$fu has qualified_name $fu_name;
$fu has commit_sha1 $commit_sha1;
$fu_def isa function-definitions has definition_count > 0;
    (has_function_definition: $fu_def, is_function_definition: $fu) isa function_definition;
$fu_copy isa function-instance;
    (has_function_definition: $fu_def, is_function_definition: $fu_copy) isa function_definition;
$fu_copy != $fu;
$dupe_fi isa file; (has_defines_function: $dupe_fi, is_defines_function: $fu_copy) isa defines_function;
$dupe_fi != $fi;
get $file_location, $fu, $fu_name, $commit_sha1;