#which methods defined by project are externally referenced (delta)
match $p isa project has project_name "<githubRepo>";
$fi isa file; (has_defines_file: $p, is_defines_file: $fi) isa defines_file;
$fi has file_location $file_location;
$real_fu isa function-instance;
$real_fu has qualified_name $fu_name;
$real_fu has commit_sha1 $commit_sha1;
	(has_defines_function: $fi, is_defines_function: $real_fu) isa defines_function;
$fu_defs isa function-definitions;
    (has_function_definition: $fu_defs, is_function_definition: $real_fu) isa function_definition;
$fu_refs isa function-references;
$open_fu isa function has reference_count $refCount;
	(has_function_definitions: $open_fu, is_function_definitions: $fu_defs) isa function_definitions;
	(has_function_references: $open_fu, is_function_references: $fu_refs) isa function_references;
$fu_ref isa function-instance has instance_offset > $refCount;
    (has_function_reference: $fu_refs, is_function_reference: $fu_ref) isa function_reference;
(has_ref_call: $fu_ref_caller, is_ref_call: $fu_ref) isa ref_call;
get $file_location, $real_fu, $fu_name, $commit_sha1, $open_fu;