#which external methods are a copy of this method
match $fu id "<id>";
$fi isa file; (has_defines_function: $fi, is_defines_function: $fu) isa defines_function;
$fu_def isa function-definitions;
    (has_function_definition: $fu_def, is_function_definition: $fu) isa function_definition;
$fu_copy isa function-instance;
    (has_function_definition: $fu_def, is_function_definition: $fu_copy) isa function_definition;
$fu_copy has commit_sha1 $commit_sha1;
$fu_copy has qualified_name $fu_name;
$fu_copy != $fu;
$dupe_fi isa file has file_location $file_location; (has_defines_function: $dupe_fi, is_defines_function: $fu_copy) isa defines_function;
$dupe_fi != $fi;
$dupe_proj isa project has project_name $p_name; (has_defines_file: $dupe_proj, is_defines_file: $dupe_fi) isa defines_file;
offset 000; limit 10; #offset is auto-updated
get $file_location, $fu_name, $commit_sha1, $p_name;