version: '3.3'
services:
  gitdetective:
    build:
      context: .
      dockerfile: Dockerfile-gitdetective
    container_name: gitdetective
    ports:
      - "8080:8080"
    restart: on-failure
  bblfshd:
    privileged: true
    image: bblfsh/bblfshd:v2.16.1-drivers-2019-10-29
    container_name: bblfshd
    ports:
      - "9432:9432"
  grakn:
    image: graknlabs/grakn:1.6.2
    container_name: grakn
    ports:
      - "48555:48555"
  timescaledb:
    image: timescale/timescaledb:latest-pg11
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"