define

##########---------- Entities ----------##########
project sub entity,
    has create_date,
    has project_name,
    plays has_defines_file;
file sub entity,
    has create_date,
    has file_name,
    has subkind,
    has file_location,
    has qualified_name,
    plays is_defines_file,
    plays has_defines_function,
    plays has_ref,
    plays has_ref_call;
function sub entity,
    has create_date,
    has function_name,
    plays has_function_references,
    plays has_function_definitions;
function-instance sub entity,
    has subkind,
    has qualified_name,
    has commit_sha1,
    has commit_date,
    plays is_function_definition,
    plays is_function_reference,
    plays is_defines_function,
    plays is_ref,
    plays is_ref_call,
    plays has_ref,
    plays has_ref_call;
function-definitions sub entity,
    plays is_function_definitions,
    plays has_function_definition;
function-references sub entity,
    plays is_function_references,
    plays has_function_reference;

##########---------- Attributes ----------##########
name sub attribute, abstract, datatype string;
create_date sub attribute, datatype string;
commit_date sub attribute, datatype string;
subkind sub attribute, datatype string;
file_location sub attribute, datatype string;
qualified_name sub name, datatype string;
commit_sha1 sub attribute, datatype string;
is_jdk sub attribute, datatype boolean;
project_name sub name, datatype string;
function_name sub name, datatype string;
file_name sub name, datatype string;
start_offset sub attribute, datatype long;
end_offset sub attribute, datatype long;

##########---------- Relationships ----------##########
#todo: can make parent relationship with create_date, start_offset, end_offset
defines sub relation, abstract,
    relates has_defines,
    relates is_defines,
    has create_date,
    has start_offset,
    has end_offset;

defines_file sub defines,
    relates has_defines_file as has_defines,
    relates is_defines_file as is_defines;

defines_function sub defines,
    relates has_defines_function as has_defines,
    relates is_defines_function as is_defines;

ref sub relation,
    relates has_ref,
    relates is_ref,
    has is_jdk,
    has create_date,
    has start_offset,
    has end_offset;

ref_call sub ref,
    relates has_ref_call as has_ref,
    relates is_ref_call as is_ref;

contains_references_and_definitions sub relation,
    relates has_contains_references_and_definitions,
    relates is_contains_references_and_definitions;

function_references sub contains_references_and_definitions,
    relates has_function_references as has_contains_references_and_definitions,
    relates is_function_references as is_contains_references_and_definitions;

function_definitions sub relation,
    relates has_function_definitions as has_contains_references_and_definitions,
    relates is_function_definitions as is_contains_references_and_definitions;

contains_function sub relation,
    relates has_contains_function,
    relates is_contains_function;

function_reference sub contains_function,
    relates has_function_reference as has_contains_function,
    relates is_function_reference as is_contains_function;

function_definition sub contains_function,
    relates has_function_definition as has_contains_function,
    relates is_function_definition as is_contains_function;
