insert $func isa function
    has calculated_reference_rounds 0
    has create_date "<createDate>"
    has function_name "<name>";
$funcDefs isa function-definitions;
    (has_function_definitions: $func, is_function_definitions: $funcDefs) isa function_definitions;
$funcRefs isa function-references;
    (has_function_references: $func, is_function_references: $funcRefs) isa function_references;