match $func1 isa! function has function_name "<funcName1>";
$funcDefs1 isa function-definitions;
    (has_function_definitions: $func1, is_function_definitions: $funcDefs1) isa function_definitions;
$func2 isa! function has function_name "<funcName2>";
$funcDefs2 isa function-definitions;
    (has_function_definitions: $func2, is_function_definitions: $funcDefs2) isa function_definitions;
$refCaller isa function-instance;
    (has_function_definition: $funcDefs1, is_function_definition: $refCaller) isa function_definition;
$refCalled isa function-instance;
    (has_function_definition: $funcDefs2, is_function_definition: $refCalled) isa function_definition;
$ref (has_ref_call: $refCaller, is_ref_call: $refCalled) isa ref_call
    has start_offset <startOffset>
    has end_offset <endOffset>;
get $ref, $func1, $func2;