match $x isa file;
$p isa project id "<projectId>"; (has_defines_file: $p, is_defines_file: $x) isa defines_file;
$y isa function-instance; (has_defines_function: $x, is_defines_function: $y) isa defines_function;
$funcDefs isa function-definitions id "<funcDefsId>";
    (has_function_definition: $funcDefs, is_function_definition: $y) isa function_definition;
$yFunc isa function; (has_function_definitions: $yFunc, is_function_definitions: $funcDefs) isa function_definitions;
$func isa function; (has_function_references: $func, is_function_references: $funcRefs) isa function_references;
$funcRef isa function-instance;
    $ref (has_ref_call: $y, is_ref_call: $funcRef) isa ref_call
        has start_offset <startOffset>
        has end_offset <endOffset>;
$funcRefs isa function-references id "<funcRefsId>";
    (has_function_reference: $funcRefs, is_function_reference: $funcRef) isa function_reference;
get $ref, $yFunc, $func;