match
    $x isa file id "<xFileId>";
    $p isa project id "<projectId>"; (has_defines_file: $p, is_defines_file: $x) isa defines_file;
    $funcDefs isa function-definitions id "<funcDefsId>";

insert
$y isa function-instance
    has commit_date "<commitDate>"
    has qualified_name "<qualifiedName>"
    has commit_sha1 "<commitSha1>";
(has_function_definition: $funcDefs, is_function_definition: $y) isa function_definition;
(has_defines_function: $x, is_defines_function: $y) isa defines_function
    has computed_instance_offset 0
    has create_date "<createDate>"
    has start_offset <startOffset>
    has end_offset <endOffset>;