match
    $x isa file id "<xFileId>";
    $funcRefs isa function-references id "<funcRefsId>";

insert
$y isa function-instance
    has instance_offset <instanceOffset>
    has create_date "<createDate>"
    has commit_date "<commitDate>"
    has qualified_name "<qualifiedName>"
    has commit_sha1 "<commitSha1>";
(has_function_reference: $funcRefs, is_function_reference: $y) isa function_reference;
(has_ref_call: $x, is_ref_call: $y) isa ref_call
    has is_jdk <isJdk>
    has create_date "<createDate>"
    has start_offset <startOffset>
    has end_offset <endOffset>;